language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

after_success:
  - mvn coveralls:report

deploy:
  - provider: script
    skip_cleanup: true
    script: src/scripts/deploy-test.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: src/scripts/deploy-prod.sh
    on:
      tags: true

after_script:
  - mvn cleanup
