language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

after_success:
  - mvn coveralls:report

deploy:
  skip_cleanup: true
  - provider: script
    script: src/scripts/deploy-test.sh
    on:
      branch: master
  - provider: script
    script: src/scripts/deploy-prod.sh
    on:
      tags: true

after_script:
  - mvn clean