language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

after_success:
  - mvn clean test jacoco:report coveralls:report

deploy:
  - provider: script
    script: awesomeagile-webapp/src/scripts/deploy-test.sh
    on:
      branch: master
