spring.datasource:
  url: jdbc:postgresql://@postgres.host@:@postgres.port@/awesomeagile-test
  username: aa_test
  password: aa_test

spring.social:
  google:
    clientId: testClientId
    secret: testSecret

